### ISSUE TITLE
Add option to download all files

### ISSUE THREAD

**Issue by spatelwearpact** [jacobdekeizer/json-to-php-generator#44]
It's a chore to copy and create files individually and would be great to be able to download them all using something like this

https://stackoverflow.com/questions/3665115/how-to-create-a-file-in-memory-for-user-to-download-but-not-through-server

Great job on the app, it works great!

**Comment by jacobdekeizer** [comment]
Hi,

There is a download button after the results header which downloads a zip file with all the generated php classes.
